// Code generated by mockery v2.36.0. DO NOT EDIT.

package logger

import mock "github.com/stretchr/testify/mock"

// MockTrimOption is an autogenerated mock type for the TrimOption type
type MockTrimOption struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *MockTrimOption) Execute(_a0 *ObjectTrimmer) {
	_m.Called(_a0)
}

// NewMockTrimOption creates a new instance of MockTrimOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTrimOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTrimOption {
	mock := &MockTrimOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
